version: "3"
services:
  web:
    build:
      context: ./scanner
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5001:5001"
    depends_on:
      - db
    links: 
      - db
      - redis

  worker:
    build:
      context: ./scanner
      dockerfile: CeleryDockerfile
    restart: on-failure
    links: 
      - db
      - redis
    depends_on:
      - redis
      - db

  db:
    image: mysql:5.7.22
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123

  redis:
    image: redis
